/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Compilador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cml_9
 */
public class ComplexJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComplexJFrame
     */
    
    Compilador c=new Compilador();
    
    public ComplexJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        CompilarButton = new javax.swing.JButton();
        CargarButton = new javax.swing.JButton();
        ArbolButton = new javax.swing.JButton();
        wolframButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CompilerTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(480, 512));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maneja tus complejos");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        CompilarButton.setBackground(new java.awt.Color(0, 51, 153));
        CompilarButton.setForeground(new java.awt.Color(255, 255, 255));
        CompilarButton.setText("Compilar");
        CompilarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompilarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(CompilarButton);

        CargarButton.setBackground(new java.awt.Color(0, 51, 153));
        CargarButton.setForeground(new java.awt.Color(255, 255, 255));
        CargarButton.setText("Cargar");
        CargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(CargarButton);

        ArbolButton.setBackground(new java.awt.Color(0, 51, 153));
        ArbolButton.setForeground(new java.awt.Color(255, 255, 255));
        ArbolButton.setText("GenerarArbol");
        ArbolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbolButtonActionPerformed(evt);
            }
        });
        jPanel5.add(ArbolButton);

        wolframButton.setBackground(new java.awt.Color(0, 51, 153));
        wolframButton.setForeground(new java.awt.Color(255, 255, 255));
        wolframButton.setText("ExportarGraficoNB");
        wolframButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wolframButtonActionPerformed(evt);
            }
        });
        jPanel5.add(wolframButton);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        CompilerTextArea.setBackground(new java.awt.Color(0, 0, 20));
        CompilerTextArea.setColumns(20);
        CompilerTextArea.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        CompilerTextArea.setForeground(new java.awt.Color(240, 240, 240));
        CompilerTextArea.setRows(5);
        CompilerTextArea.setBorder(null);
        CompilerTextArea.setMinimumSize(new java.awt.Dimension(248, 512));
        jScrollPane1.setViewportView(CompilerTextArea);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        OutputArea.setEditable(false);
        OutputArea.setBackground(new java.awt.Color(0, 0, 20));
        OutputArea.setColumns(20);
        OutputArea.setForeground(new java.awt.Color(240, 240, 240));
        OutputArea.setRows(5);
        OutputArea.setText("OutPut..");
        jScrollPane2.setViewportView(OutputArea);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompilarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompilarButtonActionPerformed
        // TODO add your handling code here:
        this.OutputArea.setText(c.compilar(this.CompilerTextArea.getText()));
    }//GEN-LAST:event_CompilarButtonActionPerformed

    private void CargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarButtonActionPerformed
        // TODO add your handling code here:
        
        this.CompilerTextArea = c.cargar(CompilerTextArea);
    }//GEN-LAST:event_CargarButtonActionPerformed

    private void ArbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbolButtonActionPerformed
        // TODO add your handling code here:
        c.showTree(this.CompilerTextArea.getText());
    }//GEN-LAST:event_ArbolButtonActionPerformed

    private void wolframButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wolframButtonActionPerformed
        try {
            // TODO add your handling code here:
            c.exportMath();
        } catch (IOException ex) {
            Logger.getLogger(ComplexJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_wolframButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplexJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArbolButton;
    private javax.swing.JButton CargarButton;
    private javax.swing.JButton CompilarButton;
    private javax.swing.JTextArea CompilerTextArea;
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton wolframButton;
    // End of variables declaration//GEN-END:variables
}
